# The path to the arduino's serial device
ARDUINO_PATH = '/dev/ttyACM0'
ARDUINO_BAUD_RATE = 9600

# The URL of the STM's schedule API
BUS_SCHEDULE_URL = "http://i-www.stm.info/en/lines/{line}/stops/{stop}/arrivals?direction={direction}&limit=5"

# The path to the balance file generated by an external script
BALANCE_PATH = "/var/www/scripts/winston_balance.txt"