# Winston configuration file
# Read the documentation to learn more about the settings below

from apscheduler.scheduler import Scheduler
import os

# The path to the arduino's serial device
ARDUINO_PATH = '/dev/ttyACM0'
ARDUINO_BAUD_RATE = 9600

# The URL of the STM's schedule API
BUS_SCHEDULE_URL = "http://i-www.stm.info/en/lines/{line}/stops/{stop}/arrivals?direction={direction}&limit=5"

# The path to the balance file generated by an external script
BALANCE_PATH = "/var/www/scripts/winston_balance.txt"

# Define your own commands and add them here
from commands import say, activate, deactivate, account_balance, open_door, set_alarm, next_bus, dinner, Command
COMMANDS = [  # The list of commands passed to the interpreter
    say.SayCommand(),  # Simple command to get started
    activate.ActivateCommand(),  # Can activate winston
    deactivate.DeactivateCommand(),  # Can deactivate winston
    account_balance.AccountBalanceCommand(),  # Lots of variation, uses regex actions
    open_door.OpenDoorCommand(),
    set_alarm.AbsoluteAlarmCommand(),
    set_alarm.RelativeAlarmCommand(),
    next_bus.NextBusCommand(),
    dinner.DinnerCommand(),
    Command(name='whatTime', actions=('what time is it',), callback=say.sayTime),  # A simple command
]

# Define a scheduler to store scheduled events
SCHEDULER = Scheduler()

# The path to the grammars used by pocketsphinx
SCRIPT_PATH = os.path.dirname(__file__)
GRAMMAR_FILE = os.path.join(SCRIPT_PATH, "grammar.fsg")
DICT_FILE = os.path.join(SCRIPT_PATH, "dict.dic")