# Winston configuration file
# Read the documentation to learn more about the settings below
from apscheduler.scheduler import Scheduler
import os

# The path to the arduino's serial device
ARDUINO_PATH = '/dev/ttyACM0'
ARDUINO_BAUD_RATE = 9600

# The URL of the STM's schedule API
BUS_SCHEDULE_URL = "http://i-www.stm.info/en/lines/{line}/stops/{stop}/arrivals?direction={direction}&limit=5"

# The path to the balance file generated by an external script
BALANCE_PATH = "/var/www/scripts/winston_balance.txt"

#Forecast.io API key
WEATHER_API_URL = 'https://api.forecast.io/forecast/e8f20d143ad3952eaccfbdc8aa4d3db3/45.4500,-73.5667?units=si&exclude=flags,minutely,hourly'

# Define a scheduler to store scheduled events
SCHEDULER = Scheduler()

# The path to the grammars used by pocketsphinx
SCRIPT_PATH = os.path.dirname(__file__)
GRAMMAR_FILE = os.path.join(SCRIPT_PATH, "grammar.fsg")
DICT_FILE = os.path.join(SCRIPT_PATH, "dict.dic")

# Define your own commands and add them here
from commands import account_balance, hello, goodbye, dinner, next_bus, set_alarm, weather, date
COMMANDS = [
    account_balance.AccountBalanceCommand(),
    hello.HelloCommand(),
    goodbye.GoodbyeCommand(),
    dinner.DinnerCommand(),
    next_bus.NextBusCommand(),
    set_alarm.RelativeAlarmCommand(),
    set_alarm.AbsoluteAlarmCommand(),
    weather.WeatherCommand(),
    date.DateTimeCommand(),
]