from utils.texttospeech import text_to_speech, spell_integer
from commands import RegexCommand
from datetime import datetime
from random import choice

class DateTimeCommand(RegexCommand):
    """
    Reads the bank account's balance from a file generated by an external script.
    """
    def __init__(self):
        """
        Build the basic regex command
        """
        regex = '(say|tell me|tell us) the (date|time)'

        super(DateTimeCommand, self).__init__(regex, True)

    def on_event(self, event, sender):
        """
        Reads the date or the time
        """
        if self.match(event['text']):
            if("time") in event['text']:
                time = datetime.now().time()
                hours = time.hour
                minutes = time.minute

                intro = (
                    'The time is',
                    'It is',
                    'It currently is',
                    'The current time is',
                )
                readable_time = "{0} {1} {2}".format(choice(intro), spell_integer(hours), spell_integer(minutes))
                text_to_speech(readable_time)
            else:
                intro = (
                    'The date is',
                    'Today is',
                )
                date = datetime.now().strftime("%B %d")
                readable_date = "{0} {1}".format(choice(intro), date)
                text_to_speech(readable_date)