from utils.texttospeech import text_to_speech, spell_integer
from commands import RegexCommand
from json import load
from urllib2 import urlopen
from config import WEATHER_URL

class WeatherCommand(RegexCommand):
    """
    Reads the bank account's balance from a file generated by an external script.
    """
    def __init__(self):
        """
        Build the basic regex command
        """
        regex = '(say|tell me|tell us) the (weather|temperature)'

        super(WeatherCommand, self).__init__(regex, True)


    def on_event(self, event, sender):
        """
        Fetches and reads the weather
        """
        if self.match(event['text']):
            try:
                data = urlopen(WEATHER_URL, timeout=5)
            except:
                text_to_speech("I am afraid I cannot get the weather, sorry.")
            else:
                cities = load(data)

                if cities['count'] == 0:
                    text_to_speech("I am afraid I cannot get the weather, sorry.")
                else:
                    city = cities['list'][0]
                    current_temp = spell_integer(int(city['main']['temp']))
                    max_temp = spell_integer(int(city['main']['temp_max']))
                    current_weather = city['weather'][0]['description']

                    output = "{weather} with a temperature of {temp} and a maximum of {maxtemp}.".format(
                        weather = current_weather,
                        temp = current_temp,
                        maxtemp = max_temp,
                    )

                    text_to_speech(output)